package proyectoalmacen;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AreaClientes extends javax.swing.JFrame {

    DefaultTableModel TablaModelo = new DefaultTableModel();

    public AreaClientes() {
        initComponents();
        String[] Apartado = new String[] { "Nombre", "Documento", "Cantida", "Correo" };
        TablaModelo.setColumnIdentifiers(Apartado);
        jTable1.setModel(TablaModelo);
        CargarDatos();
    }

    void Agregar() {
        if (contieneNumeros(Box_Nombre.getText())) {
            JOptionPane.showMessageDialog(null, "Ingresa un nombre correcto, por favor verificar.\n");
        } else if (Box_Nombre.getText().isEmpty() || Box_Documento.getText().isEmpty()
                || Box_Telefono.getText().isEmpty() || Box_Correo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresaste un lugar vacio, por favor verifica.\n");
        } else if (Box_Nombre.getText().equals("NOMBRE") || Box_Documento.getText().equals("DOCUMENTO DE IDENTIDAD")
                || Box_Telefono.getText().equals("TELEFONO") || Box_Correo.getText().equals("CORREO ELECTRONICO")) {
            JOptionPane.showMessageDialog(null, "Faltan datos por ingresar, por favor verificar.\n");
        } else {
            TablaModelo.addRow(new Object[] { Box_Nombre.getText(), Box_Documento.getText(), Box_Telefono.getText(),
                    Box_Correo.getText() });
        }
    }

    void Eliminar() {
        int fila = jTable1.getSelectedRow();

        TablaModelo.removeRow(fila);
    }

    public static boolean contieneNumeros(String palabra) {
        return palabra.matches(".*\\d.*");
    }

    void CargarDatos() {
        try {
            String Nombre = "", Documento = "", Telefono = "", Correo = "";
            String linea = "";
            FileReader Archivo = new FileReader("Stores\\Prueba_Cliente.txt");
            BufferedReader Datos = new BufferedReader(Archivo);
            linea = Datos.readLine();
            while (linea != null) {
                Nombre = linea;
                linea = Datos.readLine();
                Documento = linea;
                linea = Datos.readLine();
                Telefono = linea;
                linea = Datos.readLine();
                Correo = linea;
                linea = Datos.readLine();
                TablaModelo.addRow(new Object[] { Nombre, Documento, Telefono, Correo });
            }
            Archivo.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }

    private void Boton_CargarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            CargarDatos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_VolverMenu = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        Boton_CargarDatos = new javax.swing.JButton();
        Box_Nombre = new javax.swing.JTextField();
        Box_Telefono = new javax.swing.JTextField();
        Box_Documento = new javax.swing.JTextField();
        Box_Correo = new javax.swing.JTextField();
        Boton_Crear = new javax.swing.JButton();
        Boton_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Boton_Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 50, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_VolverMenu.setBackground(new java.awt.Color(52, 115, 85));
        Boton_VolverMenu.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Boton_VolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        Boton_VolverMenu.setText("VOLVER AL MENU");
        Boton_VolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_VolverMenuMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_VolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        Boton_Salir.setBackground(new java.awt.Color(52, 115, 85));
        Boton_Salir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Salir.setText("SALIR");
        Boton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SalirMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 130, 30));

        Boton_CargarDatos.setBackground(new java.awt.Color(52, 115, 85));
        Boton_CargarDatos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Boton_CargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        Boton_CargarDatos.setText("Cargar Datos");
        Boton_CargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_CargarDatosMouseClicked(evt);
            }
        });
        Boton_CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CargarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_CargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, 40));

        Box_Nombre.setBackground(new java.awt.Color(59, 140, 102));
        Box_Nombre.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Box_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Box_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_Nombre.setText("NOMBRE");
        Box_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Box_NombreMouseClicked(evt);
            }
        });
        jPanel1.add(Box_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 40));

        Box_Telefono.setBackground(new java.awt.Color(59, 140, 102));
        Box_Telefono.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Box_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Box_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_Telefono.setText("TELEFONO");
        Box_Telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Box_TelefonoMouseClicked(evt);
            }
        });
        jPanel1.add(Box_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 210, 40));

        Box_Documento.setBackground(new java.awt.Color(59, 140, 102));
        Box_Documento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Box_Documento.setForeground(new java.awt.Color(255, 255, 255));
        Box_Documento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_Documento.setText("DOCUMENTO DE IDENTIDAD");
        Box_Documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Box_DocumentoMouseClicked(evt);
            }
        });
        jPanel1.add(Box_Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 210, 40));

        Box_Correo.setBackground(new java.awt.Color(59, 140, 102));
        Box_Correo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Box_Correo.setForeground(new java.awt.Color(255, 255, 255));
        Box_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_Correo.setText("CORREO ELECTRONICO");
        Box_Correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Box_CorreoMouseClicked(evt);
            }
        });
        jPanel1.add(Box_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 210, 40));

        Boton_Crear.setBackground(new java.awt.Color(52, 115, 85));
        Boton_Crear.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Boton_Crear.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Crear.setText("Crear Cliente");
        Boton_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 170, 40));

        Boton_Eliminar.setBackground(new java.awt.Color(52, 115, 85));
        Boton_Eliminar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Boton_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Eliminar.setText("Eliminar Cliente");
        Boton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 170, 40));

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 490, -1));

        Boton_Guardar.setBackground(new java.awt.Color(52, 115, 85));
        Boton_Guardar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Boton_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Guardar.setText("Guardar");
        Boton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 230, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 889,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_VolverMenuMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Boton_VolverMenuMouseClicked
        try {
            Menu_Principal Menu_Principal = new Menu_Principal();
            Menu_Principal.setLocationRelativeTo(null);

            Menu_Principal.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }// GEN-LAST:event_Boton_VolverMenuMouseClicked

    void Guardar() {
        try {

            FileWriter Escribrir_Archivo = new FileWriter(
                    "C:\\Users\\Samue\\OneDrive\\Documents\\ProyectoAlmacen\\Prueba_Cliente.txt");

            for (int i = 0; i < this.TablaModelo.getRowCount(); i++) {
                Escribrir_Archivo.write(jTable1.getValueAt(i, 0).toString() + "\n");
                Escribrir_Archivo.write(jTable1.getValueAt(i, 1).toString() + "\n");
                Escribrir_Archivo.write(jTable1.getValueAt(i, 2).toString() + "\n");
                Escribrir_Archivo.write(jTable1.getValueAt(i, 3).toString() + "\n");
            }

            Escribrir_Archivo.close();
            JOptionPane.showMessageDialog(null, "Datos Guardados");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }

    }

    private void Boton_SalirMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Boton_SalirMouseClicked
        try {
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }// GEN-LAST:event_Boton_SalirMouseClicked

    private void Boton_CrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Boton_CrearActionPerformed
        Agregar();
    }// GEN-LAST:event_Boton_CrearActionPerformed

    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Boton_EliminarActionPerformed
        Eliminar();
    }// GEN-LAST:event_Boton_EliminarActionPerformed

    private void Box_NombreMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Box_NombreMouseClicked
        try {
            Box_Nombre.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }// GEN-LAST:event_Box_NombreMouseClicked

    private void Box_DocumentoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Box_DocumentoMouseClicked
        try {
            Box_Documento.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }// GEN-LAST:event_Box_DocumentoMouseClicked

    private void Box_TelefonoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Box_TelefonoMouseClicked
        try {
            Box_Telefono.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }// GEN-LAST:event_Box_TelefonoMouseClicked

    private void Box_CorreoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Box_CorreoMouseClicked
        try {
            Box_Correo.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }// GEN-LAST:event_Box_CorreoMouseClicked

    private void Boton_CargarDatosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Boton_CargarDatosMouseClicked

    }// GEN-LAST:event_Boton_CargarDatosMouseClicked

    private void Boton_CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Boton_CargarDatosActionPerformed
        CargarDatos();
    }// GEN-LAST:event_Boton_CargarDatosActionPerformed

    private void Boton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Boton_GuardarActionPerformed
        Guardar();
    }// GEN-LAST:event_Boton_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_CargarDatos;
    private javax.swing.JButton Boton_Crear;
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JButton Boton_Guardar;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Boton_VolverMenu;
    private javax.swing.JTextField Box_Correo;
    private javax.swing.JTextField Box_Documento;
    private javax.swing.JTextField Box_Nombre;
    private javax.swing.JTextField Box_Telefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
