/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoalmacen;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author Samue
 */
public class Facturacion_PuntoFisico extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Facturacion_PuntoFisico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Salir1 = new javax.swing.JButton();
        Boton_VolverMenuFacturacion1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Cantidad_Ropa = new javax.swing.JTextField();
        Cantidad_Tenis = new javax.swing.JTextField();
        Cantidad_Suministros = new javax.swing.JTextField();
        Boton_CargarCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Caja_Nombre = new javax.swing.JTextField();
        Caja_Documento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Precio_Ropa = new javax.swing.JTextField();
        Precio_Tenis = new javax.swing.JTextField();
        Precio_Suministros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Salir1.setText("SALIR");
        Boton_Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_Salir1MouseClicked(evt);
            }
        });
        jPanel1.add(Boton_Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        Boton_VolverMenuFacturacion1.setText("VOLVER AL MENU DE FACTURACION");
        Boton_VolverMenuFacturacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_VolverMenuFacturacion1MouseClicked(evt);
            }
        });
        jPanel1.add(Boton_VolverMenuFacturacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTable1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 910, 160));

        Cantidad_Ropa.setText("0");
        jPanel1.add(Cantidad_Ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 60, 30));

        Cantidad_Tenis.setText("0");
        jPanel1.add(Cantidad_Tenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 60, 30));

        Cantidad_Suministros.setText("0");
        jPanel1.add(Cantidad_Suministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 60, 30));

        Boton_CargarCompra.setText("Cargar Compra");
        jPanel1.add(Boton_CargarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 170, 40));

        jLabel1.setText("ROPA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 80, 30));

        jLabel2.setText("TENIS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 80, 30));

        jLabel3.setText("SUMINISTROS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, 30));
        jPanel1.add(Caja_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, 40));
        jPanel1.add(Caja_Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, 40));

        jLabel4.setText("CANTIDAD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 60, -1));

        jLabel5.setText("PRECIO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 100, -1));

        Precio_Ropa.setText("0");
        jPanel1.add(Precio_Ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 100, 30));

        Precio_Tenis.setText("0");
        jPanel1.add(Precio_Tenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 100, 30));

        Precio_Suministros.setText("0");
        jPanel1.add(Precio_Suministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 100, 30));

        jLabel6.setText("NOMBRE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 30));

        jLabel7.setText("DOCUMENTO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_Salir1MouseClicked
        try {
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_Salir1MouseClicked

    private void Boton_VolverMenuFacturacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_VolverMenuFacturacion1MouseClicked
        try {
            Menu_Facturacion Menu_Facturacion = new Menu_Facturacion();
            Menu_Facturacion.setLocationRelativeTo(null);
            Menu_Facturacion.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_VolverMenuFacturacion1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion_PuntoFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion_PuntoFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion_PuntoFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion_PuntoFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion_PuntoFisico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_CargarCompra;
    private javax.swing.JButton Boton_Salir1;
    private javax.swing.JButton Boton_VolverMenuFacturacion1;
    private javax.swing.JTextField Caja_Documento;
    private javax.swing.JTextField Caja_Nombre;
    private javax.swing.JTextField Cantidad_Ropa;
    private javax.swing.JTextField Cantidad_Suministros;
    private javax.swing.JTextField Cantidad_Tenis;
    private javax.swing.JTextField Precio_Ropa;
    private javax.swing.JTextField Precio_Suministros;
    private javax.swing.JTextField Precio_Tenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
