
package proyectoalmacen;
import java.io.*;
import javax.swing.*;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_Login1 = new javax.swing.JLabel();
        Panel_Login = new javax.swing.JPanel();
        Boton_Entrar = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        Texto_Login = new javax.swing.JLabel();
        Caja_Usuario = new javax.swing.JTextField();
        Caja_Contrasena = new javax.swing.JPasswordField();

        Texto_Login1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Texto_Login1.setText("LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 51, 117));

        Panel_Login.setBackground(new java.awt.Color(34, 50, 64));
        Panel_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Entrar.setBackground(new java.awt.Color(59, 140, 102));
        Boton_Entrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Entrar.setText("ENTRAR");
        Boton_Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_EntrarMouseClicked(evt);
            }
        });
        Panel_Login.add(Boton_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 50));

        Boton_Salir.setBackground(new java.awt.Color(59, 140, 102));
        Boton_Salir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Salir.setText("SALIR");
        Boton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SalirMouseClicked(evt);
            }
        });
        Panel_Login.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, 50));

        Texto_Login.setBackground(new java.awt.Color(255, 255, 255));
        Texto_Login.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        Texto_Login.setForeground(new java.awt.Color(96, 191, 129));
        Texto_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Login.setText("LOGIN");
        Panel_Login.add(Texto_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 40));

        Caja_Usuario.setBackground(new java.awt.Color(59, 140, 102));
        Caja_Usuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Caja_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Caja_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Caja_Usuario.setText("USUARIO");
        Caja_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Caja_UsuarioMouseClicked(evt);
            }
        });
        Panel_Login.add(Caja_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 50));

        Caja_Contrasena.setBackground(new java.awt.Color(59, 140, 102));
        Caja_Contrasena.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Caja_Contrasena.setForeground(new java.awt.Color(255, 255, 255));
        Caja_Contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Caja_Contrasena.setText("jPasswordField1");
        Caja_Contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Caja_ContrasenaMouseClicked(evt);
            }
        });
        Panel_Login.add(Caja_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_EntrarMouseClicked
        try {
            Menu_Principal Menu_Principal = new Menu_Principal();
            if (Archivo_Usuario_Contraseña(Caja_Usuario.getText(), Caja_Contrasena.getText()) == true) {
                Menu_Principal.setLocationRelativeTo(null);
                Menu_Principal.setVisible(true);         
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrecta. Por favor intentelo de nuevo.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_EntrarMouseClicked

    private void Caja_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Caja_UsuarioMouseClicked
        try {
            Caja_Usuario.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Caja_UsuarioMouseClicked

    private void Caja_ContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Caja_ContrasenaMouseClicked
        try {
            Caja_Contrasena.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Caja_ContrasenaMouseClicked

    private void Boton_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Boton_SalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public boolean Archivo_Usuario_Contraseña(String Usuario, String Contrasena) {
        boolean llave_acceso = false;
        String sa ="";
        try {
            String linea = "";
            FileReader Archivo = new FileReader("Stores\\Usuario_Contraseña.txt");
            BufferedReader Datos = new BufferedReader(Archivo);

            linea = Datos.readLine();
            while (linea != null) {
                if (linea.equals(Usuario)) {
                    linea = Datos.readLine();
                    if (linea.equals(Contrasena)) {
                        llave_acceso = true;
                    }
                }
                linea = Datos.readLine();
            }
            Archivo.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
        return llave_acceso;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Entrar;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JPasswordField Caja_Contrasena;
    private javax.swing.JTextField Caja_Usuario;
    private javax.swing.JPanel Panel_Login;
    private javax.swing.JLabel Texto_Login;
    private javax.swing.JLabel Texto_Login1;
    // End of variables declaration//GEN-END:variables
}
