/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoalmacen;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author Samue
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Menu_Principal = new javax.swing.JPanel();
        TextoMenuPrincipal = new javax.swing.JLabel();
        Boton_Facturacion = new javax.swing.JButton();
        Boton_Creditos = new javax.swing.JButton();
        Boton_Informes = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        Boton_Clientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Menu_Principal.setBackground(new java.awt.Color(34, 50, 64));
        Panel_Menu_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoMenuPrincipal.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        TextoMenuPrincipal.setForeground(new java.awt.Color(96, 191, 129));
        TextoMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoMenuPrincipal.setText("MENU PRINCIPAL");
        Panel_Menu_Principal.add(TextoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 620, -1));

        Boton_Facturacion.setBackground(new java.awt.Color(59, 140, 102));
        Boton_Facturacion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Facturacion.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Facturacion.setText("FACTURACION");
        Boton_Facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_FacturacionMouseClicked(evt);
            }
        });
        Panel_Menu_Principal.add(Boton_Facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 210, 60));

        Boton_Creditos.setBackground(new java.awt.Color(59, 140, 102));
        Boton_Creditos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Creditos.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Creditos.setText("CREDITOS");
        Boton_Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_CreditosMouseClicked(evt);
            }
        });
        Boton_Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CreditosActionPerformed(evt);
            }
        });
        Panel_Menu_Principal.add(Boton_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 210, 60));

        Boton_Informes.setBackground(new java.awt.Color(59, 140, 102));
        Boton_Informes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Informes.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Informes.setText("INFORMES");
        Boton_Informes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_InformesMouseClicked(evt);
            }
        });
        Panel_Menu_Principal.add(Boton_Informes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 210, 60));

        Boton_Salir.setBackground(new java.awt.Color(52, 115, 85));
        Boton_Salir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Salir.setText("SALIR");
        Boton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SalirMouseClicked(evt);
            }
        });
        Panel_Menu_Principal.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 210, 60));

        Boton_Clientes.setBackground(new java.awt.Color(59, 140, 102));
        Boton_Clientes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Clientes.setText("CLIENTES");
        Boton_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_ClientesMouseClicked(evt);
            }
        });
        Panel_Menu_Principal.add(Boton_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Menu_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Menu_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CreditosActionPerformed

    }//GEN-LAST:event_Boton_CreditosActionPerformed

    private void Boton_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SalirMouseClicked
        try {
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_SalirMouseClicked

    private void Boton_FacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_FacturacionMouseClicked
        try {
            Menu_Facturacion Menu_Facturacion = new Menu_Facturacion();
            Menu_Facturacion.setVisible(true);
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_FacturacionMouseClicked

    private void Boton_CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_CreditosMouseClicked
        try {
            Creditos Creditos = new Creditos();
            Creditos.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_CreditosMouseClicked

    private void Boton_InformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_InformesMouseClicked
        try {
            Informes Informes = new Informes();
            Informes.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_InformesMouseClicked

    private void Boton_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_ClientesMouseClicked
        try {
            AreaClientes AreaClientes = new AreaClientes();
            AreaClientes.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_ClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Clientes;
    private javax.swing.JButton Boton_Creditos;
    private javax.swing.JButton Boton_Facturacion;
    private javax.swing.JButton Boton_Informes;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JPanel Panel_Menu_Principal;
    private javax.swing.JLabel TextoMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
