/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoalmacen;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author Samue
 */
public class Menu_Facturacion extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Facturacion
     */
    public Menu_Facturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Salir = new javax.swing.JButton();
        Boton_VolverMenu = new javax.swing.JButton();
        Boton_FacturacionPuntoFisico = new javax.swing.JButton();
        Boton_FacturacionInternet = new javax.swing.JButton();
        Texto_Facturacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 50, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Salir.setBackground(new java.awt.Color(52, 115, 85));
        Boton_Salir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Salir.setText("SALIR");
        Boton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SalirMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 130, 30));

        Boton_VolverMenu.setBackground(new java.awt.Color(52, 115, 85));
        Boton_VolverMenu.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_VolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        Boton_VolverMenu.setText("VOLVER AL \nMENU");
        Boton_VolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_VolverMenuMouseClicked(evt);
            }
        });
        Boton_VolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_VolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        Boton_FacturacionPuntoFisico.setBackground(new java.awt.Color(59, 140, 102));
        Boton_FacturacionPuntoFisico.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_FacturacionPuntoFisico.setForeground(new java.awt.Color(255, 255, 255));
        Boton_FacturacionPuntoFisico.setText("PUNTO FISICO");
        Boton_FacturacionPuntoFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_FacturacionPuntoFisicoMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_FacturacionPuntoFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 170, 60));

        Boton_FacturacionInternet.setBackground(new java.awt.Color(59, 140, 102));
        Boton_FacturacionInternet.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Boton_FacturacionInternet.setForeground(new java.awt.Color(255, 255, 255));
        Boton_FacturacionInternet.setText("INTERNET");
        Boton_FacturacionInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_FacturacionInternetMouseClicked(evt);
            }
        });
        jPanel1.add(Boton_FacturacionInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 170, 60));

        Texto_Facturacion.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        Texto_Facturacion.setForeground(new java.awt.Color(96, 191, 129));
        Texto_Facturacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Facturacion.setText("FACTURACION");
        jPanel1.add(Texto_Facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SalirMouseClicked
        try {
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_SalirMouseClicked

    private void Boton_VolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_VolverMenuMouseClicked
        try {
            Menu_Principal Menu_Principal = new Menu_Principal();
            Menu_Principal.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_VolverMenuMouseClicked

    private void Boton_FacturacionPuntoFisicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_FacturacionPuntoFisicoMouseClicked
        try {
            Facturacion_PuntoFisico Facturacion_PuntoFisico = new Facturacion_PuntoFisico();
            Facturacion_PuntoFisico.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }

    }//GEN-LAST:event_Boton_FacturacionPuntoFisicoMouseClicked

    private void Boton_FacturacionInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_FacturacionInternetMouseClicked
        try {
            Facturacion_Internet Facturacion_Internet = new Facturacion_Internet();
            Facturacion_Internet.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error:\n" + ex);
        }
    }//GEN-LAST:event_Boton_FacturacionInternetMouseClicked

    private void Boton_VolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_VolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_FacturacionInternet;
    private javax.swing.JButton Boton_FacturacionPuntoFisico;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Boton_VolverMenu;
    private javax.swing.JLabel Texto_Facturacion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
